version: '2'
 
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
 
  app:
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/inep_api'
    volumes_from:
    - box

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
 
  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box: